### ISSUE TITLE
coala-bears does not detect missing dependency 'pyreadline'. Gives 'No bears matching' warnings instead.

### ISSUE THREAD

**Issue by jsecrest** [coala/coala-bears#2535]
### Issue summary

1. When installing with pipenv on Windows 10 with coala, coala-bears does get install all dependencies. It misses `pyreadline` unless coala-bears is installed separately. (unsure if this is anything we can fix or not)
2. Coala-bears does not detect the missing dependency. Instead it runs and gives a missing bear warning, even when bears are installed to the correct locations.

### Details
I use pipenv to manage my projects in a Windows 10 environment. I've been having a problem where I get missing bear warnings even after installing coala with
`python -m pipenv install coala coala-bears`

I looked in the virtual environment files and saw that the bears I needed did exist there. e.g.: this folder contained the PEP8Bear that coala said was missing.
 `C:\Users\example_user\.virtualenvs\example_project-HrhRq8XW\Lib\site-packages\bears\python`

After a lot of tinkering I found that if I tried to install coala-bears separately after the install the bears were detected
`python -m pipenv install coala-bears`

I reproduced the problem and solution a few times (though only in one environment), and then started watching the install output when installing coala-bears for the second time. I see that a missing dependency is installed:
```text
[...]
Collecting pyreadline~=2.1; platform_system == "Windows" (from coala-utils~=0.6.2->coala~=0.11.0->coala-bears)
[...]
Installing collected packages: pyreadline
Successfully installed pyreadline-2.1
```

This problem also occurs if I install with `python -m pipenv install` from an existing Pipfile that includes both coala and coala-bears. I can fix this the same way, by installing coala-bears again separately after the install.

**Comment by jsecrest** [comment]
The cause of the missing dependency is probably related to https://github.com/pypa/pipenv/issues/1757, which is supposedly resolved by one of their recent commits. However, we should still notice and report the missing dependency instead of reporting a missing bear.

**Comment by jayvdb** [comment]
That dependency is in the coala project https://gitlab.com/coala/coala-utils/ (on GitLab).  Could you re-analyse the problem in that context and possible raise an issue in that project.

It may be that the problem is fixed there, but hasnt been released, and thus the problem is still occurring when installing coala-bears.  In which case, the solution is ... wait ... we'll do a release soon ;-)
